"""unique chat participants

Revision ID: 21f8b5fc316b
Revises: b875511063f0
Create Date: 2026-02-18 16:31:52.020148

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21f8b5fc316b"
down_revision: Union[str, Sequence[str], None] = "b875511063f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_chat_participants_chat_id_user_id",
        "chat_participants",
        ["chat_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_chat_participants_chat_id_user_id", "chat_participants", type_="unique"
    )
    # ### end Alembic commands ###
