"""add client_msg_id in messages

Revision ID: 96bbc9c949ce
Revises: 0045d165fdbb
Create Date: 2025-09-26 20:03:09.582035

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96bbc9c949ce"
down_revision: Union[str, Sequence[str], None] = "0045d165fdbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("client_msg_id", sa.UUID(), nullable=False))
    op.create_unique_constraint(
        "uq_messages_client_msg_id", "messages", ["client_msg_id"]
    )
    op.create_unique_constraint(None, "messages", ["client_msg_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="unique")
    op.drop_constraint("uq_messages_client_msg_id", "messages", type_="unique")
    op.drop_column("messages", "client_msg_id")
    # ### end Alembic commands ###
